version: '3'

services:
  game:
    image: ggjnez92/dev-game:1.2
    restart: always
    container_name: 'dev-game'
    ports:
      - '127.0.0.1:8820:80'
    volumes:
      - $DB_DATA_PATH:/data/db
    env_file:
      - .env
